import Sidebar from "@/components/Sidebar";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  const toggleMode = () => {
    setDarkMode(!darkMode);
  };

  return (
    <>
      <Head>
        <title>Manage Your Team's Projects</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/icon.png' />
      </Head>
      <main className={darkMode ? "dark" : ""}>
        <section className='min-h-screen bg-white dark:bg-black/90 flex'>
          <Sidebar toggleMode={toggleMode} darkMode={darkMode} />
        </section>
      </main>
    </>
  );
}
